// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Dirs", testDirsUpsert)

	t.Run("Files", testFilesUpsert)

	t.Run("RegisterRequests", testRegisterRequestsUpsert)

	t.Run("ResetTokens", testResetTokensUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Trashes", testTrashesUpsert)

	t.Run("Users", testUsersUpsert)
}
