// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRegisterRequests(t *testing.T) {
	t.Parallel()

	query := RegisterRequests()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRegisterRequestsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRegisterRequestsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RegisterRequests().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRegisterRequestsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RegisterRequestSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRegisterRequestsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RegisterRequestExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if RegisterRequest exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RegisterRequestExists to return true, but got false.")
	}
}

func testRegisterRequestsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	registerRequestFound, err := FindRegisterRequest(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if registerRequestFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRegisterRequestsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RegisterRequests().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRegisterRequestsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RegisterRequests().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRegisterRequestsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	registerRequestOne := &RegisterRequest{}
	registerRequestTwo := &RegisterRequest{}
	if err = randomize.Struct(seed, registerRequestOne, registerRequestDBTypes, false, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}
	if err = randomize.Struct(seed, registerRequestTwo, registerRequestDBTypes, false, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = registerRequestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = registerRequestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RegisterRequests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRegisterRequestsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	registerRequestOne := &RegisterRequest{}
	registerRequestTwo := &RegisterRequest{}
	if err = randomize.Struct(seed, registerRequestOne, registerRequestDBTypes, false, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}
	if err = randomize.Struct(seed, registerRequestTwo, registerRequestDBTypes, false, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = registerRequestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = registerRequestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func registerRequestBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *RegisterRequest) error {
	*o = RegisterRequest{}
	return nil
}

func registerRequestAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *RegisterRequest) error {
	*o = RegisterRequest{}
	return nil
}

func registerRequestAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *RegisterRequest) error {
	*o = RegisterRequest{}
	return nil
}

func registerRequestBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RegisterRequest) error {
	*o = RegisterRequest{}
	return nil
}

func registerRequestAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RegisterRequest) error {
	*o = RegisterRequest{}
	return nil
}

func registerRequestBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RegisterRequest) error {
	*o = RegisterRequest{}
	return nil
}

func registerRequestAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RegisterRequest) error {
	*o = RegisterRequest{}
	return nil
}

func registerRequestBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RegisterRequest) error {
	*o = RegisterRequest{}
	return nil
}

func registerRequestAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RegisterRequest) error {
	*o = RegisterRequest{}
	return nil
}

func testRegisterRequestsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &RegisterRequest{}
	o := &RegisterRequest{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, registerRequestDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RegisterRequest object: %s", err)
	}

	AddRegisterRequestHook(boil.BeforeInsertHook, registerRequestBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	registerRequestBeforeInsertHooks = []RegisterRequestHook{}

	AddRegisterRequestHook(boil.AfterInsertHook, registerRequestAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	registerRequestAfterInsertHooks = []RegisterRequestHook{}

	AddRegisterRequestHook(boil.AfterSelectHook, registerRequestAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	registerRequestAfterSelectHooks = []RegisterRequestHook{}

	AddRegisterRequestHook(boil.BeforeUpdateHook, registerRequestBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	registerRequestBeforeUpdateHooks = []RegisterRequestHook{}

	AddRegisterRequestHook(boil.AfterUpdateHook, registerRequestAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	registerRequestAfterUpdateHooks = []RegisterRequestHook{}

	AddRegisterRequestHook(boil.BeforeDeleteHook, registerRequestBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	registerRequestBeforeDeleteHooks = []RegisterRequestHook{}

	AddRegisterRequestHook(boil.AfterDeleteHook, registerRequestAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	registerRequestAfterDeleteHooks = []RegisterRequestHook{}

	AddRegisterRequestHook(boil.BeforeUpsertHook, registerRequestBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	registerRequestBeforeUpsertHooks = []RegisterRequestHook{}

	AddRegisterRequestHook(boil.AfterUpsertHook, registerRequestAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	registerRequestAfterUpsertHooks = []RegisterRequestHook{}
}

func testRegisterRequestsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRegisterRequestsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(registerRequestColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRegisterRequestsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRegisterRequestsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RegisterRequestSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRegisterRequestsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RegisterRequests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	registerRequestDBTypes = map[string]string{`ID`: `uuid`, `Name`: `character varying`, `Email`: `character varying`, `Grade`: `integer`, `CreatedAt`: `timestamp without time zone`}
	_                      = bytes.MinRead
)

func testRegisterRequestsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(registerRequestPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(registerRequestAllColumns) == len(registerRequestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRegisterRequestsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(registerRequestAllColumns) == len(registerRequestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RegisterRequest{}
	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, registerRequestDBTypes, true, registerRequestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(registerRequestAllColumns, registerRequestPrimaryKeyColumns) {
		fields = registerRequestAllColumns
	} else {
		fields = strmangle.SetComplement(
			registerRequestAllColumns,
			registerRequestPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RegisterRequestSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRegisterRequestsUpsert(t *testing.T) {
	t.Parallel()

	if len(registerRequestAllColumns) == len(registerRequestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RegisterRequest{}
	if err = randomize.Struct(seed, &o, registerRequestDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RegisterRequest: %s", err)
	}

	count, err := RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, registerRequestDBTypes, false, registerRequestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RegisterRequest struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RegisterRequest: %s", err)
	}

	count, err = RegisterRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
