// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TeacherReviewedFile is an object representing the database table.
type TeacherReviewedFile struct {
	ID         string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ReviewedID string    `boil:"reviewed_id" json:"reviewed_id" toml:"reviewed_id" yaml:"reviewed_id"`
	FileName   string    `boil:"file_name" json:"file_name" toml:"file_name" yaml:"file_name"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *teacherReviewedFileR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L teacherReviewedFileL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TeacherReviewedFileColumns = struct {
	ID         string
	ReviewedID string
	FileName   string
	CreatedAt  string
}{
	ID:         "id",
	ReviewedID: "reviewed_id",
	FileName:   "file_name",
	CreatedAt:  "created_at",
}

var TeacherReviewedFileTableColumns = struct {
	ID         string
	ReviewedID string
	FileName   string
	CreatedAt  string
}{
	ID:         "teacher_reviewed_files.id",
	ReviewedID: "teacher_reviewed_files.reviewed_id",
	FileName:   "teacher_reviewed_files.file_name",
	CreatedAt:  "teacher_reviewed_files.created_at",
}

// Generated where

var TeacherReviewedFileWhere = struct {
	ID         whereHelperstring
	ReviewedID whereHelperstring
	FileName   whereHelperstring
	CreatedAt  whereHelpertime_Time
}{
	ID:         whereHelperstring{field: "`teacher_reviewed_files`.`id`"},
	ReviewedID: whereHelperstring{field: "`teacher_reviewed_files`.`reviewed_id`"},
	FileName:   whereHelperstring{field: "`teacher_reviewed_files`.`file_name`"},
	CreatedAt:  whereHelpertime_Time{field: "`teacher_reviewed_files`.`created_at`"},
}

// TeacherReviewedFileRels is where relationship names are stored.
var TeacherReviewedFileRels = struct {
	Reviewed string
}{
	Reviewed: "Reviewed",
}

// teacherReviewedFileR is where relationships are stored.
type teacherReviewedFileR struct {
	Reviewed *Reviewed `boil:"Reviewed" json:"Reviewed" toml:"Reviewed" yaml:"Reviewed"`
}

// NewStruct creates a new relationship struct
func (*teacherReviewedFileR) NewStruct() *teacherReviewedFileR {
	return &teacherReviewedFileR{}
}

func (r *teacherReviewedFileR) GetReviewed() *Reviewed {
	if r == nil {
		return nil
	}
	return r.Reviewed
}

// teacherReviewedFileL is where Load methods for each relationship are stored.
type teacherReviewedFileL struct{}

var (
	teacherReviewedFileAllColumns            = []string{"id", "reviewed_id", "file_name", "created_at"}
	teacherReviewedFileColumnsWithoutDefault = []string{"id", "reviewed_id", "file_name"}
	teacherReviewedFileColumnsWithDefault    = []string{"created_at"}
	teacherReviewedFilePrimaryKeyColumns     = []string{"id"}
	teacherReviewedFileGeneratedColumns      = []string{}
)

type (
	// TeacherReviewedFileSlice is an alias for a slice of pointers to TeacherReviewedFile.
	// This should almost always be used instead of []TeacherReviewedFile.
	TeacherReviewedFileSlice []*TeacherReviewedFile
	// TeacherReviewedFileHook is the signature for custom TeacherReviewedFile hook methods
	TeacherReviewedFileHook func(context.Context, boil.ContextExecutor, *TeacherReviewedFile) error

	teacherReviewedFileQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	teacherReviewedFileType                 = reflect.TypeOf(&TeacherReviewedFile{})
	teacherReviewedFileMapping              = queries.MakeStructMapping(teacherReviewedFileType)
	teacherReviewedFilePrimaryKeyMapping, _ = queries.BindMapping(teacherReviewedFileType, teacherReviewedFileMapping, teacherReviewedFilePrimaryKeyColumns)
	teacherReviewedFileInsertCacheMut       sync.RWMutex
	teacherReviewedFileInsertCache          = make(map[string]insertCache)
	teacherReviewedFileUpdateCacheMut       sync.RWMutex
	teacherReviewedFileUpdateCache          = make(map[string]updateCache)
	teacherReviewedFileUpsertCacheMut       sync.RWMutex
	teacherReviewedFileUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var teacherReviewedFileAfterSelectHooks []TeacherReviewedFileHook

var teacherReviewedFileBeforeInsertHooks []TeacherReviewedFileHook
var teacherReviewedFileAfterInsertHooks []TeacherReviewedFileHook

var teacherReviewedFileBeforeUpdateHooks []TeacherReviewedFileHook
var teacherReviewedFileAfterUpdateHooks []TeacherReviewedFileHook

var teacherReviewedFileBeforeDeleteHooks []TeacherReviewedFileHook
var teacherReviewedFileAfterDeleteHooks []TeacherReviewedFileHook

var teacherReviewedFileBeforeUpsertHooks []TeacherReviewedFileHook
var teacherReviewedFileAfterUpsertHooks []TeacherReviewedFileHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TeacherReviewedFile) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teacherReviewedFileAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TeacherReviewedFile) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teacherReviewedFileBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TeacherReviewedFile) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teacherReviewedFileAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TeacherReviewedFile) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teacherReviewedFileBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TeacherReviewedFile) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teacherReviewedFileAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TeacherReviewedFile) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teacherReviewedFileBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TeacherReviewedFile) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teacherReviewedFileAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TeacherReviewedFile) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teacherReviewedFileBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TeacherReviewedFile) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teacherReviewedFileAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTeacherReviewedFileHook registers your hook function for all future operations.
func AddTeacherReviewedFileHook(hookPoint boil.HookPoint, teacherReviewedFileHook TeacherReviewedFileHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		teacherReviewedFileAfterSelectHooks = append(teacherReviewedFileAfterSelectHooks, teacherReviewedFileHook)
	case boil.BeforeInsertHook:
		teacherReviewedFileBeforeInsertHooks = append(teacherReviewedFileBeforeInsertHooks, teacherReviewedFileHook)
	case boil.AfterInsertHook:
		teacherReviewedFileAfterInsertHooks = append(teacherReviewedFileAfterInsertHooks, teacherReviewedFileHook)
	case boil.BeforeUpdateHook:
		teacherReviewedFileBeforeUpdateHooks = append(teacherReviewedFileBeforeUpdateHooks, teacherReviewedFileHook)
	case boil.AfterUpdateHook:
		teacherReviewedFileAfterUpdateHooks = append(teacherReviewedFileAfterUpdateHooks, teacherReviewedFileHook)
	case boil.BeforeDeleteHook:
		teacherReviewedFileBeforeDeleteHooks = append(teacherReviewedFileBeforeDeleteHooks, teacherReviewedFileHook)
	case boil.AfterDeleteHook:
		teacherReviewedFileAfterDeleteHooks = append(teacherReviewedFileAfterDeleteHooks, teacherReviewedFileHook)
	case boil.BeforeUpsertHook:
		teacherReviewedFileBeforeUpsertHooks = append(teacherReviewedFileBeforeUpsertHooks, teacherReviewedFileHook)
	case boil.AfterUpsertHook:
		teacherReviewedFileAfterUpsertHooks = append(teacherReviewedFileAfterUpsertHooks, teacherReviewedFileHook)
	}
}

// One returns a single teacherReviewedFile record from the query.
func (q teacherReviewedFileQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TeacherReviewedFile, error) {
	o := &TeacherReviewedFile{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for teacher_reviewed_files")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TeacherReviewedFile records from the query.
func (q teacherReviewedFileQuery) All(ctx context.Context, exec boil.ContextExecutor) (TeacherReviewedFileSlice, error) {
	var o []*TeacherReviewedFile

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TeacherReviewedFile slice")
	}

	if len(teacherReviewedFileAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TeacherReviewedFile records in the query.
func (q teacherReviewedFileQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count teacher_reviewed_files rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q teacherReviewedFileQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if teacher_reviewed_files exists")
	}

	return count > 0, nil
}

// Reviewed pointed to by the foreign key.
func (o *TeacherReviewedFile) Reviewed(mods ...qm.QueryMod) reviewedQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.ReviewedID),
	}

	queryMods = append(queryMods, mods...)

	return Revieweds(queryMods...)
}

// LoadReviewed allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (teacherReviewedFileL) LoadReviewed(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTeacherReviewedFile interface{}, mods queries.Applicator) error {
	var slice []*TeacherReviewedFile
	var object *TeacherReviewedFile

	if singular {
		var ok bool
		object, ok = maybeTeacherReviewedFile.(*TeacherReviewedFile)
		if !ok {
			object = new(TeacherReviewedFile)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTeacherReviewedFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTeacherReviewedFile))
			}
		}
	} else {
		s, ok := maybeTeacherReviewedFile.(*[]*TeacherReviewedFile)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTeacherReviewedFile)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTeacherReviewedFile))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &teacherReviewedFileR{}
		}
		args = append(args, object.ReviewedID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teacherReviewedFileR{}
			}

			for _, a := range args {
				if a == obj.ReviewedID {
					continue Outer
				}
			}

			args = append(args, obj.ReviewedID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`reviewed`),
		qm.WhereIn(`reviewed.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Reviewed")
	}

	var resultSlice []*Reviewed
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Reviewed")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for reviewed")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for reviewed")
	}

	if len(teacherReviewedFileAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Reviewed = foreign
		if foreign.R == nil {
			foreign.R = &reviewedR{}
		}
		foreign.R.TeacherReviewedFiles = append(foreign.R.TeacherReviewedFiles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ReviewedID == foreign.ID {
				local.R.Reviewed = foreign
				if foreign.R == nil {
					foreign.R = &reviewedR{}
				}
				foreign.R.TeacherReviewedFiles = append(foreign.R.TeacherReviewedFiles, local)
				break
			}
		}
	}

	return nil
}

// SetReviewed of the teacherReviewedFile to the related item.
// Sets o.R.Reviewed to related.
// Adds o to related.R.TeacherReviewedFiles.
func (o *TeacherReviewedFile) SetReviewed(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Reviewed) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `teacher_reviewed_files` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"reviewed_id"}),
		strmangle.WhereClause("`", "`", 0, teacherReviewedFilePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ReviewedID = related.ID
	if o.R == nil {
		o.R = &teacherReviewedFileR{
			Reviewed: related,
		}
	} else {
		o.R.Reviewed = related
	}

	if related.R == nil {
		related.R = &reviewedR{
			TeacherReviewedFiles: TeacherReviewedFileSlice{o},
		}
	} else {
		related.R.TeacherReviewedFiles = append(related.R.TeacherReviewedFiles, o)
	}

	return nil
}

// TeacherReviewedFiles retrieves all the records using an executor.
func TeacherReviewedFiles(mods ...qm.QueryMod) teacherReviewedFileQuery {
	mods = append(mods, qm.From("`teacher_reviewed_files`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`teacher_reviewed_files`.*"})
	}

	return teacherReviewedFileQuery{q}
}

// FindTeacherReviewedFile retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTeacherReviewedFile(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*TeacherReviewedFile, error) {
	teacherReviewedFileObj := &TeacherReviewedFile{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `teacher_reviewed_files` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, teacherReviewedFileObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from teacher_reviewed_files")
	}

	if err = teacherReviewedFileObj.doAfterSelectHooks(ctx, exec); err != nil {
		return teacherReviewedFileObj, err
	}

	return teacherReviewedFileObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TeacherReviewedFile) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no teacher_reviewed_files provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(teacherReviewedFileColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	teacherReviewedFileInsertCacheMut.RLock()
	cache, cached := teacherReviewedFileInsertCache[key]
	teacherReviewedFileInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			teacherReviewedFileAllColumns,
			teacherReviewedFileColumnsWithDefault,
			teacherReviewedFileColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(teacherReviewedFileType, teacherReviewedFileMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(teacherReviewedFileType, teacherReviewedFileMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `teacher_reviewed_files` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `teacher_reviewed_files` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `teacher_reviewed_files` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, teacherReviewedFilePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into teacher_reviewed_files")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for teacher_reviewed_files")
	}

CacheNoHooks:
	if !cached {
		teacherReviewedFileInsertCacheMut.Lock()
		teacherReviewedFileInsertCache[key] = cache
		teacherReviewedFileInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TeacherReviewedFile.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TeacherReviewedFile) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	teacherReviewedFileUpdateCacheMut.RLock()
	cache, cached := teacherReviewedFileUpdateCache[key]
	teacherReviewedFileUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			teacherReviewedFileAllColumns,
			teacherReviewedFilePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update teacher_reviewed_files, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `teacher_reviewed_files` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, teacherReviewedFilePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(teacherReviewedFileType, teacherReviewedFileMapping, append(wl, teacherReviewedFilePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update teacher_reviewed_files row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for teacher_reviewed_files")
	}

	if !cached {
		teacherReviewedFileUpdateCacheMut.Lock()
		teacherReviewedFileUpdateCache[key] = cache
		teacherReviewedFileUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q teacherReviewedFileQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for teacher_reviewed_files")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for teacher_reviewed_files")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TeacherReviewedFileSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teacherReviewedFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `teacher_reviewed_files` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, teacherReviewedFilePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in teacherReviewedFile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all teacherReviewedFile")
	}
	return rowsAff, nil
}

// Delete deletes a single TeacherReviewedFile record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TeacherReviewedFile) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TeacherReviewedFile provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), teacherReviewedFilePrimaryKeyMapping)
	sql := "DELETE FROM `teacher_reviewed_files` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from teacher_reviewed_files")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for teacher_reviewed_files")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q teacherReviewedFileQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no teacherReviewedFileQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from teacher_reviewed_files")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for teacher_reviewed_files")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TeacherReviewedFileSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(teacherReviewedFileBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teacherReviewedFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `teacher_reviewed_files` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, teacherReviewedFilePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from teacherReviewedFile slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for teacher_reviewed_files")
	}

	if len(teacherReviewedFileAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TeacherReviewedFile) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTeacherReviewedFile(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TeacherReviewedFileSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TeacherReviewedFileSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teacherReviewedFilePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `teacher_reviewed_files`.* FROM `teacher_reviewed_files` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, teacherReviewedFilePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TeacherReviewedFileSlice")
	}

	*o = slice

	return nil
}

// TeacherReviewedFileExists checks if the TeacherReviewedFile row exists.
func TeacherReviewedFileExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `teacher_reviewed_files` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if teacher_reviewed_files exists")
	}

	return exists, nil
}

var mySQLTeacherReviewedFileUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TeacherReviewedFile) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no teacher_reviewed_files provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(teacherReviewedFileColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTeacherReviewedFileUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	teacherReviewedFileUpsertCacheMut.RLock()
	cache, cached := teacherReviewedFileUpsertCache[key]
	teacherReviewedFileUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			teacherReviewedFileAllColumns,
			teacherReviewedFileColumnsWithDefault,
			teacherReviewedFileColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			teacherReviewedFileAllColumns,
			teacherReviewedFilePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert teacher_reviewed_files, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`teacher_reviewed_files`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `teacher_reviewed_files` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(teacherReviewedFileType, teacherReviewedFileMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(teacherReviewedFileType, teacherReviewedFileMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for teacher_reviewed_files")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(teacherReviewedFileType, teacherReviewedFileMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for teacher_reviewed_files")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for teacher_reviewed_files")
	}

CacheNoHooks:
	if !cached {
		teacherReviewedFileUpsertCacheMut.Lock()
		teacherReviewedFileUpsertCache[key] = cache
		teacherReviewedFileUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
